'use strict';

const alb_metrics = {
  ActiveConnectionCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NewConnectionCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  RejectedConnectionCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  RequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_4XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  HTTPCode_ELB_5XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  TargetResponseTime: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  TargetTLSNegotiationErrorCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TargetConnectionErrorCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Target_2XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Target_3XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Target_4XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  HTTPCode_Target_5XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ProcessedBytes: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  TargetTLSHandshakeErrorCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_2XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_3XX_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ClientTLSNegotiationErrorCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ConsumedLCUs: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DesyncMitigationMode_NonCompliant_Request_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DroppedInvalidHeaderRequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ForwardedInvalidHeaderRequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GrpcRequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTP_Fixed_Response_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTP_Redirect_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTP_Redirect_Url_Limit_Exceeded_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_500_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_502_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_503_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_ELB_504_Count: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  IPv6ProcessedBytes: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  IPv6RequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NonStickyRequestCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  RuleEvaluations: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HealthyHostCount: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  LambdaInternalError: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  LambdaUserError: {
    dimensions: [{ Name: 'LoadBalancer', Value: '' }],
    namespace: 'AWS/ApplicationELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { alb_metrics };
