'use strict';

const apigateway_metrics = {
  Latency: {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  Count: {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  IntegrationLatency: {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Milliseconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  '4XXError': {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  '5XXError': {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CacheHitCount: {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CacheMissCount: {
    dimensions: [{ Name: 'ApiName', Value: '' }],
    namespace: 'AWS/ApiGateway',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
};

module.exports = { apigateway_metrics };
