'use strict';

const asg_metrics = {
  GroupTotalInstances: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolTerminatingCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupInServiceInstances: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'None',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'LessThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'None',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  GroupInServiceCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupPendingCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupPendingInstances: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupAndWarmPoolTotalCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupTerminatingInstances: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolMinSize: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupDesiredCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupMaxSize: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolPendingCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupStandbyCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolTotalCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupAndWarmPoolDesiredCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolWarmedCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupTerminatingCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  WarmPoolDesiredCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupTotalCapacity: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupStandbyInstances: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GroupMinSize: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/AutoScaling',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  // ASG reports EC2 metrics under the EC2 namespace
  CPUUtilization: {
    dimensions: [{ Name: 'AutoScalingGroupName', Value: '' }],
    namespace: 'AWS/EC2',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { asg_metrics };
