'use strict';

const cloudfront_metrics = {
  '4xxErrorRate': {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 1000,
      evaluation_periods: 10,
      period: 60,
      statistic: 'Average',
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      threshold_type: 'Static',
      unit: 'Percent',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  '5xxErrorRate': {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 100,
      evaluation_periods: 10,
      period: 60,
      statistic: 'Average',
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      threshold_type: 'Static',
      unit: 'Percent',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  TotalErrorRate: {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 100,
      evaluation_periods: 10,
      period: 60,
      statistic: 'Average',
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      threshold_type: 'Static',
      unit: 'Percent',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CacheHitRate: {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 70,
      evaluation_periods: 15,
      period: 60,
      statistic: 'Average',
      threshold_condition: 'LessThanOrEqualToThreshold',
      threshold_type: 'Static',
      unit: 'Percent',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  OriginLatency: {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Percentile',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesDownloaded: {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesUploaded: {
    dimensions: [{ Name: 'Region', Value: 'Global' }, { Name: 'DistributionId', Value: '' }],
    namespace: 'AWS/CloudFront',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
};

module.exports = { cloudfront_metrics };
