'use strict';

const dms_instance_metrics = {
  CPUUtilization: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 300000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  FreeStorageSpace: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 10000000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadIOPS: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteIOPS: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 5000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  DiskQueueDepth: {
    dimensions: [{ Name: 'ReplicationInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DMS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const dms_task_metrics = {
  CDCIncomingChanges: {
    dimensions: [
      { Name: 'ReplicationTaskIdentifier', Value: '' },
      { Name: 'ReplicationInstanceIdentifier', Value: '' },
    ],
    namespace: 'AWS/DMS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 5000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CDCLatencySource: {
    dimensions: [
      { Name: 'ReplicationTaskIdentifier', Value: '' },
      { Name: 'ReplicationInstanceIdentifier', Value: '' },
    ],
    namespace: 'AWS/DMS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 30,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CDCLatencyTarget: {
    dimensions: [
      { Name: 'ReplicationTaskIdentifier', Value: '' },
      { Name: 'ReplicationInstanceIdentifier', Value: '' },
    ],
    namespace: 'AWS/DMS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 30,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { dms_instance_metrics, dms_task_metrics };
