'use strict';

const docdb_metrics = {
  DatabaseConnections: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  SwapUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  WriteIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  DiskQueueDepth: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkTransmitThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkReceiveThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  ReadThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  WriteThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUSurplusCreditsCharged: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUSurplusCreditBalance: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditBalance: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 60,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUCreditUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
};

const docdb_cluster_metrics = {
  DatabaseConnections: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  VolumeReadIOPs: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  VolumeWriteIOPs: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/DocDB',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
};

module.exports = { docdb_metrics, docdb_cluster_metrics };
