'use strict';

const dynamodb_metrics = {
  AccountMaxReads: {
    dimensions: [],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  AccountMaxTableLevelReads: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  AccountMaxTableLevelWrites: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  AccountMaxWrites: {
    dimensions: [],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  AccountProvisionedReadCapacityUtilization: {
    dimensions: [],
    namespace: 'AWS/DynamoDB',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  AccountProvisionedWriteCapacityUtilization: {
    dimensions: [],
    namespace: 'AWS/DynamoDB',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  AgeOfOldestUnreplicatedRecord: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Seconds',
    global_threshold: null,
    metric_weight: 1,
  },
  ConditionalCheckFailedRequests: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ConsumedChangeDataCaptureUnits: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ConsumedReadCapacityUnits: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ConsumedWriteCapacityUnits: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  FailedToReplicateRecordCount: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  MaxProvisionedTableReadCapacityUtilization: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  MaxProvisionedTableWriteCapacityUtilization: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  OnlineIndexConsumedWriteCapacity: {
    dimensions: [{ Name: 'TableName', Value: '' }, { Name: 'IndexName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  OnlineIndexPercentageProgress: {
    dimensions: [{ Name: 'TableName', Value: '' }, { Name: 'IndexName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  OnlineIndexThrottleEvents: {
    dimensions: [{ Name: 'TableName', Value: '' }, { Name: 'IndexName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  PendingReplicationCount: {
    dimensions: [],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ProvisionedReadCapacityUnits: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ProvisionedWriteCapacityUnits: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ReadThrottleEvents: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReplicationLatency: {
    dimensions: [{ Name: 'TableName', Value: '' }, { Name: 'ReceivingRegion', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Milliseconds',
    global_threshold: {
      threshold_value: 10000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReturnedBytes: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  ReturnedItemCount: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ReturnedRecordsCount: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  SuccessfulRequestLatency: {
    dimensions: [{ Name: 'TableName', Value: '' }, { Name: 'Operation', Value: 'Query' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Milliseconds',
    global_threshold: {
      threshold_value: 500,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  SystemErrors: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TimeToLiveDeletedItemCount: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ThrottledPutRecordCount: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ThrottledRequests: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TransactionConflict: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  UserErrors: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  WriteThrottleEvents: {
    dimensions: [{ Name: 'TableName', Value: '' }],
    namespace: 'AWS/DynamoDB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { dynamodb_metrics };
