'use strict';

const ecs_metrics = {
  CPUUtilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  MemoryUtilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CPUReservation: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  MemoryReservation: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HTTPCode_Target_4XX_Count: {
    dimensions: [{ Name: 'ServiceName', Value: '' }, { Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Target_5XX_Count: {
    dimensions: [{ Name: 'ServiceName', Value: '' }, { Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TargetResponseTime: {
    dimensions: [{ Name: 'ServiceName', Value: '' }, { Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Milliseconds',
    global_threshold: null,
    metric_weight: 1,
  },
};

const ecs_service_metrics = {
  CPUUtilization: {
    dimensions: [{ Name: 'ServiceName', Value: '' }, { Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  MemoryUtilization: {
    dimensions: [{ Name: 'ServiceName', Value: '' }, { Name: 'ClusterName', Value: '' }],
    namespace: 'AWS/ECS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const ecs_instance_metrics = {
  instance_cpu_utilization: {
    dimensions: [
      { Name: 'ClusterName', Value: '' },
      { Name: 'InstanceId', Value: '' },
      { Name: 'ContainerInstanceId', Value: '' },
    ],
    namespace: 'ECS/ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  instance_memory_utilization: {
    dimensions: [
      { Name: 'ClusterName', Value: '' },
      { Name: 'InstanceId', Value: '' },
      { Name: 'ContainerInstanceId', Value: '' },
    ],
    namespace: 'ECS/ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  instance_filesystem_utilization: {
    dimensions: [
      { Name: 'ClusterName', Value: '' },
      { Name: 'InstanceId', Value: '' },
      { Name: 'ContainerInstanceId', Value: '' },
    ],
    namespace: 'ECS/ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const ecs_discovery_metrics = {
  HTTPCode_Target_4XX_Count: {
    dimensions: [
      { Name: 'TargetDiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: null,
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  HTTPCode_Target_5XX_Count: {
    dimensions: [
      { Name: 'TargetDiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  HTTPCode_Target_3XX_Count: {
    dimensions: [
      { Name: 'TargetDiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    unit: 'Count',
    global_threshold: null,
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  RequestCount: {
    dimensions: [
      { Name: 'DiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  GrpcRequestCount: {
    dimensions: [
      { Name: 'DiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  TargetResponseTime: {
    dimensions: [
      { Name: 'TargetDiscoveryName', Value: '' },
      { Name: 'ServiceName', Value: '' },
      { Name: 'ClusterName', Value: '' },
    ],
    namespace: 'AWS/ECS',
    unit: 'Milliseconds',
    global_threshold: {
      threshold_value: 2000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { ecs_metrics, ecs_service_metrics, ecs_instance_metrics, ecs_discovery_metrics };
