'use strict';

const eks_container_insights_metrics = {
  node_memory_utilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  node_cpu_utilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  node_cpu_reserved_capacity: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  node_filesystem_utilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  node_memory_reserved_capacity: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  pod_memory_utilization_over_pod_limit: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  pod_memory_utilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  pod_cpu_utilization: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  pod_cpu_reserved_capacity: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  pod_memory_reserved_capacity: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  pod_cpu_utilization_over_pod_limit: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  cluster_failed_node_count: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'ContainerInsights',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  disk_used_percent: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'CWAgent',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  mem_used_percent: {
    dimensions: [{ Name: 'ClusterName', Value: '' }],
    namespace: 'CWAgent',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { eks_container_insights_metrics };
