'use strict';

const elb_metrics = {
  HealthyHostCount: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'LessThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  UnHealthyHostCount: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  RequestCount: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Latency: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HTTPCode_Backend_2XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Backend_3XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  HTTPCode_Backend_4XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HTTPCode_Backend_5XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HTTPCode_ELB_4XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HTTPCode_ELB_5XX: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  BackendConnectionErrors: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  SurgeQueueLength: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  SpilloverCount: {
    dimensions: [{ Name: 'LoadBalancerName', Value: '' }],
    namespace: 'AWS/ELB',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { elb_metrics };
