'use strict';

const kafka_metrics = {
  ActiveControllerCount: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  GlobalTopicCount: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 5000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  KafkaDataLogsDiskUsed: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 300,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  OfflinePartitionsCount: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 0,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 300,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const kafka_broker_metrics = {
  CpuUser: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  UnderReplicatedPartitions: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 0,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  KafkaDataLogsDiskUsed: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CPUCreditBalance: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HeapMemoryAfterGC: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 60,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  PartitionCount: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 4000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  UnderMinIsrPartitionCount: {
    namespace: 'AWS/Kafka',
    dimensions: [{ Name: 'Cluster Name', Value: '' }, { Name: 'Broker ID', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 0,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { kafka_metrics, kafka_broker_metrics };
