'use strict';

const lambda_metrics = {
  Invocations: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Errors: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  DeadLetterErrors: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Duration: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Milliseconds',
    global_threshold: {
      threshold_value: 100000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  Throttles: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  DestinationDeliveryFailures: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Sum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  IteratorAge: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Milliseconds',
    global_threshold: null,
    metric_weight: 1,
  },
  ConcurrentExecutions: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Count',
    global_threshold: {
      threshold_value: 950,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  AsyncEventAge: {
    dimensions: [{ Name: 'FunctionName', Value: '' }],
    namespace: 'AWS/Lambda',
    unit: 'Milliseconds',
    global_threshold: null,
    metric_weight: 1,
  },
  memory_utilization: {
    // function_name is a custom Lambda Insights dimension — not the standard FunctionName
    dimensions: [{ Name: 'function_name', Value: '' }],
    namespace: 'LambdaInsights',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { lambda_metrics };
