'use strict';

const memcached_metrics = {
  CPUUtilization: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  SwapUsage: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkPacketsOut: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditUsage: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Credits (vCPU-minutes)',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditBalance: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Credits (vCPU-minutes)',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBytesIn: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBytesOut: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkPacketsIn: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesWrittenOutFromMemcached: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  CasBadval: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CasHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesReadIntoMemcached: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdGet: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdTouch: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdFlush: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CasMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DecrHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DecrMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesUsedForHash: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  IncrMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesUsedForCacheItems: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  EvictedUnfetched: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DeleteMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GetMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CurrConfig: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  IncrHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  DeleteHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ExpiredUnfetched: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdConfigGet: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdConfigSet: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TouchHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TouchMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CrawlerItemsChecked: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  UnusedMemory: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NewItems: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  GetHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CmdSet: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Evictions: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: {
      threshold_value: 500,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { memcached_metrics };
