'use strict';

const opensearch_metrics = {
  SearchLatency: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Milliseconds',
    global_threshold: {
      threshold_value: 500,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Milliseconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Percent',
    },
    metric_weight: 1,
  },
  JVMMemoryPressure: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Percent',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Seconds',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.5,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Seconds',
    },
    metric_weight: 1,
  },
  '5xx': {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Count',
    },
    metric_weight: 1,
  },
  '4xx': {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Count',
    global_threshold: {
      threshold_value: 500,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Count',
    },
    metric_weight: 1,
  },
  MasterCPUUtilization: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      unit: 'Percent',
    },
    metric_weight: 1,
  },
  SearchRate: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Count',
    global_threshold: null,
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerOrGreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  IndexingRate: {
    dimensions: [{ Name: 'DomainName', Value: '' }, { Name: 'ClientId', Value: '' }],
    namespace: 'AWS/ES',
    unit: 'Count',
    global_threshold: null,
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerOrGreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { opensearch_metrics };
