'use strict';

const rabbitmq_metrics = {
  ConnectionCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  RabbitMQDiskFree: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 10000000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  RabbitMQMemUsed: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 1000000000,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  SystemCpuUtilization: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  QueueCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  MessageCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  MessageReadyCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const active_mq_metrics = {
  BurstBalance: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CpuCreditBalance: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CpuUtilization: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  CurrentConnectionsCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HeapUsage: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  StorePercentUsage: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  TotalMessageCount: {
    namespace: 'AWS/AmazonMQ',
    dimensions: [{ Name: 'Broker', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { rabbitmq_metrics, active_mq_metrics };
