'use strict';

const rds_metrics = {
  ReplicationSlotDiskUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  TransactionLogsDiskUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  DatabaseConnections: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  FreeStorageSpace: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 2000000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  SwapUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 300,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
      enabled: false,
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Dynamic',
      enabled: false,
    },
    metric_weight: 1,
  },
  WriteIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 300,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
      enabled: false,
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Dynamic',
      enabled: false,
    },
    metric_weight: 1,
  },
  DiskQueueDepth: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkTransmitThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkReceiveThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  MaximumUsedTransactionIDs: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  OldestReplicationSlotLag: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: null,
    metric_weight: 1,
  },
  ReadThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  WriteThroughput: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  'EBSIOBalance%': {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  'EBSByteBalance%': {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUSurplusCreditsCharged: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUSurplusCreditBalance: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  TransactionLogsGeneration: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditBalance: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 60,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUCreditUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BurstBalance: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  DBLoad: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: null,
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: null,
      threshold_type: 'Static',
      enabled: false,
    },
    metric_weight: 1,
  },
  DBLoadNonCPU: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: null,
    metric_weight: 1,
  },
  DBLoadCPU: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    global_threshold: {
      threshold_value: 4,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      enabled: false,
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  LVMWriteIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  BinLogDiskUsage: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  LVMReadIOPS: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  ReplicaLag: {
    dimensions: [{ Name: 'DBInstanceIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 10,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

const rds_cluster_metrics = {
  DatabaseConnections: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 0.2,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  Deadlocks: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditBalance: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUCreditUsage: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  VolumeReadIOPs: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
      enabled: false,
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
      enabled: false,
    },
    metric_weight: 1,
  },
  VolumeWriteIOPs: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
      enabled: false,
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Dynamic',
      enabled: false,
    },
    metric_weight: 1,
  },
  DBLoadCPU: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    global_threshold: {
      threshold_value: 4,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      threshold_type: 'Static',
      enabled: false,
    },
    metric_weight: 1,
  },
  DBLoad: {
    dimensions: [{ Name: 'DBClusterIdentifier', Value: '' }],
    namespace: 'AWS/RDS',
    unit: null,
    global_threshold: {
      threshold_value: 100,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: null,
      threshold_type: 'Static',
      enabled: false,
    },
    metric_weight: 1,
  },
};

module.exports = { rds_metrics, rds_cluster_metrics };
