'use strict';

const redis_metrics = {
  NonKeyTypeCmdsLatency: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Microseconds',
    global_threshold: null,
    metric_weight: 1,
  },
  NonKeyTypeCmds: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  IamAuthenticationThrottling: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  IamAuthenticationExpirations: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Reclaimed: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NewConnections: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  Evictions: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: {
      threshold_value: 500,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CacheHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CacheMisses: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ReplicationBytes: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  ActiveDefragHits: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Number',
    global_threshold: null,
    metric_weight: 1,
  },
  KeyAuthorizationFailures: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  AuthenticationFailures: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  KeysTracked: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CommandAuthorizationFailures: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBytesIn: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBytesOut: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkPacketsIn: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBandwidthOutAllowanceExceeded: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkConntrackAllowanceExceeded: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkPacketsPerSecondAllowanceExceeded: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkBandwidthInAllowanceExceeded: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CurrConnections: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  BytesUsedForCache: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  TrafficManagementActive: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Boolean',
    global_threshold: null,
    metric_weight: 1,
  },
  SaveInProgress: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Boolean',
    global_threshold: null,
    metric_weight: 1,
  },
  CurrItems: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  CurrVolatileItems: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  ReplicationLag: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Seconds',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUUtilization: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  FreeableMemory: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: {
      threshold_value: 500000000,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Bytes',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  SwapUsage: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Bytes',
    global_threshold: null,
    metric_weight: 1,
  },
  NetworkPacketsOut: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: null,
    metric_weight: 1,
  },
  EngineCPUUtilization: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CPUCreditUsage: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Credits (vCPU-minutes)',
    global_threshold: null,
    metric_weight: 1,
  },
  CPUCreditBalance: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Credits (vCPU-minutes)',
    global_threshold: null,
    metric_weight: 1,
  },
  DatabaseMemoryUsagePercentage: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 90,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  CacheHitRate: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Percent',
    global_threshold: {
      threshold_value: 30,
      threshold_condition: 'LessThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'LessThanLowerThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 15,
      unit: 'Percent',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
  ChannelAuthorizationFailures: {
    dimensions: [{ Name: 'CacheClusterId', Value: '' }],
    namespace: 'AWS/ElastiCache',
    unit: 'Count',
    global_threshold: {
      threshold_value: 50,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    global_threshold_dynamic: {
      deviation_count: 10,
      threshold_condition: 'GreaterThanUpperThreshold',
      statistic: 'Average',
      period: 60,
      evaluation_periods: 5,
      unit: 'Count',
      threshold_type: 'Dynamic',
    },
    metric_weight: 1,
  },
};

module.exports = { redis_metrics };
