'use strict';

const redshift_metrics = {
  CPUUtilization: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HealthStatus: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'LessThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  PercentageDiskSpaceUsed: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadIOPS: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteIOPS: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  DatabaseConnections: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

const redshift_node_metrics = {
  CPUUtilization: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  HealthStatus: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Count',
    global_threshold: {
      threshold_value: 1,
      threshold_condition: 'LessThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  PercentageDiskSpaceUsed: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Percent',
    global_threshold: {
      threshold_value: 80,
      threshold_condition: 'GreaterThanOrEqualToThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Percent',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadIOPS: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteIOPS: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Count/Second',
    global_threshold: {
      threshold_value: 1000,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Count/Second',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  ReadLatency: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
  WriteLatency: {
    namespace: 'AWS/Redshift',
    dimensions: [{ Name: 'ClusterIdentifier', Value: '' }, { Name: 'NodeID', Value: '' }],
    unit: 'Seconds',
    global_threshold: {
      threshold_value: 20,
      threshold_condition: 'GreaterThanThreshold',
      statistic: 'Maximum',
      period: 60,
      evaluation_periods: 10,
      unit: 'Seconds',
      threshold_type: 'Static',
    },
    metric_weight: 1,
  },
};

module.exports = { redshift_metrics, redshift_node_metrics };
